// PostgreSQL engine, no network/daemon. Run: npm ci && node replica-journal.mjs
import {PGlite} from '@electric-sql/pglite';
import assert from 'node:assert/strict';
import {readFile,readdir,writeFile,mkdir} from 'node:fs/promises';
const db=new PGlite();
const dir=new URL('../../migrations/',import.meta.url);
const migrations=(await readdir(dir)).filter(f=>f.endsWith('.sql')).sort();
for(const f of migrations) await db.exec(await readFile(new URL(f,dir),'utf8'));
console.log(`PASS: all ${migrations.length} migrations on PostgreSQL`);
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const user=id(1), workspace=id(2), board=id(3), column=id(4), card=id(5);
const q=async(sql,args=[]) => (await db.query(sql,args)).rows;
await db.exec(`insert into users(id,email,display_name) values('${user}','regression@example.test','owner');
insert into workspaces(id,name,owner_user_id) values('${workspace}','w','${user}');
insert into boards(id,workspace_id,name) values('${board}','${workspace}','b');
insert into board_columns(id,board_id,name,position) values('${column}','${board}','c',1000);
insert into cards(id,board_id,column_id,title,position) values('${card}','${board}','${column}','first',1000);`);
async function activity(n,kind='card.updated',entityType='card',entityId=card,fields=['title']){
 await q(`insert into activity_entries(id,workspace_id,board_id,card_id,kind,entity_type,entity_id,field_mask) values($1,$2,$3,$4,$5,$6,$7,$8)`,[id(n),workspace,board,card,kind,entityType,entityId,fields]);
 return (await q('select id,event_json from roaming_board_outbox where source_activity_id=$1',[id(n)]))[0];
}
await db.exec('begin');
const first=await activity(6,'card.created','card',card,['*']);
assert.equal(first.event_json.payload.card.title,'first');
assert.equal((await q('select count(*)::int n from roaming_field_versions where event_id=$1',[first.event_json.eventId]))[0].n,10);
assert.equal((await q('select status from roaming_board_events where event_id=$1',[first.event_json.eventId]))[0].status,'applied');
await db.exec('commit');
console.log('PASS: local intent, immutable event and field versions committed atomically');
if(process.env.REPLICA_FIXTURE_PATH) await writeFile(process.env.REPLICA_FIXTURE_PATH,JSON.stringify(first.event_json,null,2)+'\n');
await q('update cards set title=$2 where id=$1',[card,'later']);
await q("update roaming_board_outbox set status='retry' where id=$1",[first.id]);
assert.deepEqual((await q('select event_json from roaming_board_outbox where id=$1',[first.id]))[0].event_json,first.event_json);
const second=await activity(7);
assert.deepEqual(second.event_json.fieldMask,['title']);
assert.equal(second.event_json.payload.card.title,'later');
assert.ok(second.event_json.logicalClock>first.event_json.logicalClock);
console.log('PASS: retry cannot substitute later state; new intent receives a new clock');
await db.exec('begin');
await q('update cards set title=$2 where id=$1',[card,'rollback']);
const rolled=await activity(8);
await db.exec('rollback');
assert.equal((await q('select title from cards where id=$1',[card]))[0].title,'later');
assert.equal((await q('select count(*)::int n from roaming_board_events where event_id=$1',[rolled.event_json.eventId]))[0].n,0);
console.log('PASS: transaction rollback removes event and its field stamps');
// Old pending row may already have been published with different content.
await q('update roaming_board_outbox set event_json=null where id=$1',[first.id]);
await q("update roaming_board_outbox set status='retry' where id=$1",[first.id]);
const repaired=(await q('select event_json from roaming_board_outbox where id=$1',[first.id]))[0].event_json;
assert.notEqual(repaired.eventId,first.event_json.eventId);
assert.equal(repaired.entityId,card);
console.log('PASS: recovery of unfrozen legacy outbox uses a fresh event identity');
const future=Date.now()*1000+100000000;
await q(`insert into roaming_board_events(event_id,nostr_event_id,author_public_key,workspace_id,board_id,replica_id,replica_seq,logical_clock,entity_id,operation,status) values($1,'remote-fixture','peer',$2,$3,$4,1,$5,$6,'card.put','applied')`,[id(20),workspace,board,id(21),future,card]);
const afterFuture=await activity(9);
assert.ok(afterFuture.event_json.logicalClock>future);
console.log('PASS: local Lamport clock advances beyond an observed peer clock');
const checklist=id(30), item=id(31);
await q('insert into checklists(id,card_id,title,position) values($1,$2,$3,1000)',[checklist,card,'list']);
await q('insert into checklist_items(id,checklist_id,title,position) values($1,$2,$3,1000)',[item,checklist,'item']);
const listEvent=await activity(32,'checklist.created','checklist',checklist,['*']);
assert.equal(listEvent.event_json.payload.checklistDelta.kind,'checklist.put');
const itemEvent=await activity(33,'checklist_item.created','checklist_item',item,['*']);
assert.equal(itemEvent.event_json.payload.checklistDelta.item.id,item);
await q('update checklist_items set deleted_at=now() where id=$1',[item]);
const deleteEvent=await activity(34,'checklist_item.deleted','checklist_item',item,['__lifecycle']);
assert.equal(deleteEvent.event_json.payload.checklistDelta.kind,'checklist_item.delete');
assert.equal((await q("select event_id from roaming_field_versions where entity_id=$1 and field_name='checklist_item.__lifecycle'",[item]))[0].event_id,deleteEvent.event_json.eventId);
const snapshot=(await q('select roaming_board_snapshot($1) snapshot',[board]))[0].snapshot;
assert.equal(snapshot.checklistsByCardId[card][0].items.length,0);
assert.equal(snapshot.schemaVersion,6);
console.log('PASS: checklist lifecycle deltas and baseline omit deleted items');
const beforeRemote=(await q('select count(*)::int n from roaming_board_outbox'))[0].n;
await q(`insert into activity_entries(id,workspace_id,board_id,card_id,kind,entity_type,entity_id,payload_jsonb) values($1,$2,$3,$4,'card.updated','card',$4,'{"source":"roaming"}')`,[id(40),workspace,board,card]);
assert.equal((await q('select count(*)::int n from roaming_board_outbox'))[0].n,beforeRemote);
console.log('PASS: imported relay activity is not republished as new local intent');
await db.close();
